/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  fragment cart on Cart {\n    id\n    checkoutUrl\n    cost {\n      totalAmount {\n        amount\n        currencyCode\n      }\n      subtotalAmount {\n        amount\n        currencyCode\n      }\n    }\n    lines(first: 20) {\n      edges {\n        node {\n          cost {\n            amountPerQuantity {\n              amount\n              currencyCode\n            }\n            totalAmount {\n              amount\n              currencyCode\n            }\n            subtotalAmount {\n              amount\n              currencyCode\n            }\n            compareAtAmountPerQuantity {\n              amount\n              currencyCode\n            }\n          }\n          quantity\n          merchandise {\n            ... on ProductVariant {\n              title\n              sku\n              image {\n                id\n                url\n                width\n                height\n                altText\n                thumbhash\n              }\n              product {\n                handle\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.CartFragmentDoc,
    "\n  mutation addCartLines($cartId: ID!, $lines: [CartLineInput!]!) {\n    cartLinesAdd(cartId: $cartId, lines: $lines) {\n      cart {\n        ...cart\n      }\n    }\n  }\n": typeof types.AddCartLinesDocument,
    "\n  mutation createCart($input: CartInput) {\n    cartCreate(input: $input) {\n      cart {\n        ...cart\n      }\n    }\n  }\n": typeof types.CreateCartDocument,
    "\n  query cart($id: ID!) {\n    cart(id: $id) {\n      ...cart\n    }\n  }\n": typeof types.CartDocument,
    "\n  query product($handle: String!) {\n    product(handle: $handle) {\n      id\n      tags\n      title\n      handle\n      vendor\n      description\n      productType\n      totalInventory\n      priceRange {\n        minVariantPrice {\n          amount\n        }\n        maxVariantPrice {\n          amount\n        }\n      }\n      selectedOrFirstAvailableVariant {\n        id\n        sku\n        price {\n          amount\n          currencyCode\n        }\n        quantityAvailable\n      }\n      options {\n        id\n        name\n        optionValues {\n          id\n          name\n          swatch {\n            color\n            image {\n              previewImage {\n                url\n                thumbhash\n              }\n            }\n          }\n          firstSelectableVariant {\n            sku\n            price {\n              amount\n              currencyCode\n            }\n          }\n        }\n      }\n      category {\n        id\n        name\n        ancestors {\n          id\n          name\n          ancestors {\n            id\n            name\n          }\n        }\n      }\n      media(first: 10) {\n        edges {\n          node {\n            alt\n            previewImage {\n              id\n              url\n              width\n              height\n              altText\n              thumbhash\n            }\n            mediaContentType\n          }\n        }\n      }\n    }\n  }\n": typeof types.ProductDocument,
    "\n  query products($first: Int = 20) {\n    products(first: $first) {\n      edges {\n        node {\n          id\n          title\n          handle\n          vendor\n          productType\n          variantsCount {\n            count\n            precision\n          }\n          media(first: 2) {\n            edges {\n              node {\n                id\n                alt\n                mediaContentType\n                previewImage {\n                  url\n                  width\n                  height\n                  altText\n                  thumbhash\n                }\n              }\n            }\n          }\n          priceRange {\n            minVariantPrice {\n              amount\n            }\n            maxVariantPrice {\n              amount\n            }\n          }\n          selectedOrFirstAvailableVariant {\n            image {\n              url\n            }\n            id\n            sku\n            price {\n              amount\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.ProductsDocument,
};
const documents: Documents = {
    "\n  fragment cart on Cart {\n    id\n    checkoutUrl\n    cost {\n      totalAmount {\n        amount\n        currencyCode\n      }\n      subtotalAmount {\n        amount\n        currencyCode\n      }\n    }\n    lines(first: 20) {\n      edges {\n        node {\n          cost {\n            amountPerQuantity {\n              amount\n              currencyCode\n            }\n            totalAmount {\n              amount\n              currencyCode\n            }\n            subtotalAmount {\n              amount\n              currencyCode\n            }\n            compareAtAmountPerQuantity {\n              amount\n              currencyCode\n            }\n          }\n          quantity\n          merchandise {\n            ... on ProductVariant {\n              title\n              sku\n              image {\n                id\n                url\n                width\n                height\n                altText\n                thumbhash\n              }\n              product {\n                handle\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.CartFragmentDoc,
    "\n  mutation addCartLines($cartId: ID!, $lines: [CartLineInput!]!) {\n    cartLinesAdd(cartId: $cartId, lines: $lines) {\n      cart {\n        ...cart\n      }\n    }\n  }\n": types.AddCartLinesDocument,
    "\n  mutation createCart($input: CartInput) {\n    cartCreate(input: $input) {\n      cart {\n        ...cart\n      }\n    }\n  }\n": types.CreateCartDocument,
    "\n  query cart($id: ID!) {\n    cart(id: $id) {\n      ...cart\n    }\n  }\n": types.CartDocument,
    "\n  query product($handle: String!) {\n    product(handle: $handle) {\n      id\n      tags\n      title\n      handle\n      vendor\n      description\n      productType\n      totalInventory\n      priceRange {\n        minVariantPrice {\n          amount\n        }\n        maxVariantPrice {\n          amount\n        }\n      }\n      selectedOrFirstAvailableVariant {\n        id\n        sku\n        price {\n          amount\n          currencyCode\n        }\n        quantityAvailable\n      }\n      options {\n        id\n        name\n        optionValues {\n          id\n          name\n          swatch {\n            color\n            image {\n              previewImage {\n                url\n                thumbhash\n              }\n            }\n          }\n          firstSelectableVariant {\n            sku\n            price {\n              amount\n              currencyCode\n            }\n          }\n        }\n      }\n      category {\n        id\n        name\n        ancestors {\n          id\n          name\n          ancestors {\n            id\n            name\n          }\n        }\n      }\n      media(first: 10) {\n        edges {\n          node {\n            alt\n            previewImage {\n              id\n              url\n              width\n              height\n              altText\n              thumbhash\n            }\n            mediaContentType\n          }\n        }\n      }\n    }\n  }\n": types.ProductDocument,
    "\n  query products($first: Int = 20) {\n    products(first: $first) {\n      edges {\n        node {\n          id\n          title\n          handle\n          vendor\n          productType\n          variantsCount {\n            count\n            precision\n          }\n          media(first: 2) {\n            edges {\n              node {\n                id\n                alt\n                mediaContentType\n                previewImage {\n                  url\n                  width\n                  height\n                  altText\n                  thumbhash\n                }\n              }\n            }\n          }\n          priceRange {\n            minVariantPrice {\n              amount\n            }\n            maxVariantPrice {\n              amount\n            }\n          }\n          selectedOrFirstAvailableVariant {\n            image {\n              url\n            }\n            id\n            sku\n            price {\n              amount\n            }\n          }\n        }\n      }\n    }\n  }\n": types.ProductsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment cart on Cart {\n    id\n    checkoutUrl\n    cost {\n      totalAmount {\n        amount\n        currencyCode\n      }\n      subtotalAmount {\n        amount\n        currencyCode\n      }\n    }\n    lines(first: 20) {\n      edges {\n        node {\n          cost {\n            amountPerQuantity {\n              amount\n              currencyCode\n            }\n            totalAmount {\n              amount\n              currencyCode\n            }\n            subtotalAmount {\n              amount\n              currencyCode\n            }\n            compareAtAmountPerQuantity {\n              amount\n              currencyCode\n            }\n          }\n          quantity\n          merchandise {\n            ... on ProductVariant {\n              title\n              sku\n              image {\n                id\n                url\n                width\n                height\n                altText\n                thumbhash\n              }\n              product {\n                handle\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment cart on Cart {\n    id\n    checkoutUrl\n    cost {\n      totalAmount {\n        amount\n        currencyCode\n      }\n      subtotalAmount {\n        amount\n        currencyCode\n      }\n    }\n    lines(first: 20) {\n      edges {\n        node {\n          cost {\n            amountPerQuantity {\n              amount\n              currencyCode\n            }\n            totalAmount {\n              amount\n              currencyCode\n            }\n            subtotalAmount {\n              amount\n              currencyCode\n            }\n            compareAtAmountPerQuantity {\n              amount\n              currencyCode\n            }\n          }\n          quantity\n          merchandise {\n            ... on ProductVariant {\n              title\n              sku\n              image {\n                id\n                url\n                width\n                height\n                altText\n                thumbhash\n              }\n              product {\n                handle\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation addCartLines($cartId: ID!, $lines: [CartLineInput!]!) {\n    cartLinesAdd(cartId: $cartId, lines: $lines) {\n      cart {\n        ...cart\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation addCartLines($cartId: ID!, $lines: [CartLineInput!]!) {\n    cartLinesAdd(cartId: $cartId, lines: $lines) {\n      cart {\n        ...cart\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createCart($input: CartInput) {\n    cartCreate(input: $input) {\n      cart {\n        ...cart\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createCart($input: CartInput) {\n    cartCreate(input: $input) {\n      cart {\n        ...cart\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query cart($id: ID!) {\n    cart(id: $id) {\n      ...cart\n    }\n  }\n"): (typeof documents)["\n  query cart($id: ID!) {\n    cart(id: $id) {\n      ...cart\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query product($handle: String!) {\n    product(handle: $handle) {\n      id\n      tags\n      title\n      handle\n      vendor\n      description\n      productType\n      totalInventory\n      priceRange {\n        minVariantPrice {\n          amount\n        }\n        maxVariantPrice {\n          amount\n        }\n      }\n      selectedOrFirstAvailableVariant {\n        id\n        sku\n        price {\n          amount\n          currencyCode\n        }\n        quantityAvailable\n      }\n      options {\n        id\n        name\n        optionValues {\n          id\n          name\n          swatch {\n            color\n            image {\n              previewImage {\n                url\n                thumbhash\n              }\n            }\n          }\n          firstSelectableVariant {\n            sku\n            price {\n              amount\n              currencyCode\n            }\n          }\n        }\n      }\n      category {\n        id\n        name\n        ancestors {\n          id\n          name\n          ancestors {\n            id\n            name\n          }\n        }\n      }\n      media(first: 10) {\n        edges {\n          node {\n            alt\n            previewImage {\n              id\n              url\n              width\n              height\n              altText\n              thumbhash\n            }\n            mediaContentType\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query product($handle: String!) {\n    product(handle: $handle) {\n      id\n      tags\n      title\n      handle\n      vendor\n      description\n      productType\n      totalInventory\n      priceRange {\n        minVariantPrice {\n          amount\n        }\n        maxVariantPrice {\n          amount\n        }\n      }\n      selectedOrFirstAvailableVariant {\n        id\n        sku\n        price {\n          amount\n          currencyCode\n        }\n        quantityAvailable\n      }\n      options {\n        id\n        name\n        optionValues {\n          id\n          name\n          swatch {\n            color\n            image {\n              previewImage {\n                url\n                thumbhash\n              }\n            }\n          }\n          firstSelectableVariant {\n            sku\n            price {\n              amount\n              currencyCode\n            }\n          }\n        }\n      }\n      category {\n        id\n        name\n        ancestors {\n          id\n          name\n          ancestors {\n            id\n            name\n          }\n        }\n      }\n      media(first: 10) {\n        edges {\n          node {\n            alt\n            previewImage {\n              id\n              url\n              width\n              height\n              altText\n              thumbhash\n            }\n            mediaContentType\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query products($first: Int = 20) {\n    products(first: $first) {\n      edges {\n        node {\n          id\n          title\n          handle\n          vendor\n          productType\n          variantsCount {\n            count\n            precision\n          }\n          media(first: 2) {\n            edges {\n              node {\n                id\n                alt\n                mediaContentType\n                previewImage {\n                  url\n                  width\n                  height\n                  altText\n                  thumbhash\n                }\n              }\n            }\n          }\n          priceRange {\n            minVariantPrice {\n              amount\n            }\n            maxVariantPrice {\n              amount\n            }\n          }\n          selectedOrFirstAvailableVariant {\n            image {\n              url\n            }\n            id\n            sku\n            price {\n              amount\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query products($first: Int = 20) {\n    products(first: $first) {\n      edges {\n        node {\n          id\n          title\n          handle\n          vendor\n          productType\n          variantsCount {\n            count\n            precision\n          }\n          media(first: 2) {\n            edges {\n              node {\n                id\n                alt\n                mediaContentType\n                previewImage {\n                  url\n                  width\n                  height\n                  altText\n                  thumbhash\n                }\n              }\n            }\n          }\n          priceRange {\n            minVariantPrice {\n              amount\n            }\n            maxVariantPrice {\n              amount\n            }\n          }\n          selectedOrFirstAvailableVariant {\n            image {\n              url\n            }\n            id\n            sku\n            price {\n              amount\n            }\n          }\n        }\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;