/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  fragment asset on Asset {\n    __typename\n    url\n    size\n    title\n    width\n    height\n    contentType\n  }\n": typeof types.AssetFragmentDoc,
    "\n  fragment brandBanner on BrandBanner {\n    __typename\n    bannerItemsCollection(limit: 20) {\n      items {\n        ... on ContentfulImage {\n          image {\n            ... on Asset {\n              __typename\n              url\n              size\n              title\n              width\n              height\n              contentType\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.BrandBannerFragmentDoc,
    "\n  fragment contentRow on ContentRow {\n    __typename\n    type\n    numberOfColumns\n    contentCollection(limit: 4) {\n      items {\n        ...splash\n      }\n    }\n  }\n": typeof types.ContentRowFragmentDoc,
    "\n  fragment footerBanner on FooterBanner {\n    __typename\n    ... on FooterBanner {\n      title\n      linkText\n      desktopImage {\n        ...asset\n      }\n      mobileImage {\n        ...asset\n      }\n    }\n  }\n": typeof types.FooterBannerFragmentDoc,
    "\n  fragment productList on ProductList {\n    __typename\n    linkText\n    heading\n    commerceData\n  }\n": typeof types.ProductListFragmentDoc,
    "\n  fragment splash on Splash {\n    __typename\n    header\n    subheading\n    linkText\n    textColor\n    contentPosition\n    desktopVideo {\n      ...asset\n    }\n    desktopImage {\n      ...asset\n    }\n    mobileVideo {\n      ...asset\n    }\n    mobileImage {\n      ...asset\n    }\n    href {\n      ... on Page {\n        __typename\n        slug\n      }\n      ... on EditorialPage {\n        __typename\n        slug\n      }\n      ... on Campaign {\n        __typename\n        slug\n      }\n      ... on LandingPage {\n        __typename\n        slug\n      }\n      ... on NavigationLink {\n        title\n        internalLink {\n          ... on Page {\n            __typename\n            slug\n          }\n          ... on EditorialPage {\n            __typename\n            slug\n          }\n          ... on Campaign {\n            __typename\n            slug\n          }\n          ... on LandingPage {\n            __typename\n            slug\n          }\n        }\n      }\n    }\n  }\n": typeof types.SplashFragmentDoc,
    "\n  fragment textBlock on TextBlock {\n    __typename\n    title\n    content {\n      json\n      links {\n        entries {\n          hyperlink {\n            ... on Page {\n              __typename\n              slug\n            }\n            ... on EditorialPage {\n              __typename\n              slug\n            }\n            ... on Campaign {\n              __typename\n              slug\n            }\n            ... on LandingPage {\n              __typename\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.TextBlockFragmentDoc,
    "\n  query landingPage(\n    $order: LandingPageOrder = sys_publishedAt_DESC\n    $where: LandingPageFilter\n    $skip: Int = 0\n    $limit: Int = 1\n    $locale: String\n    $preview: Boolean = false\n  ) {\n    landingPageCollection(\n      order: [$order]\n      limit: $limit\n      where: $where\n      preview: $preview\n      locale: $locale\n      skip: $skip\n    ) {\n      items {\n        title\n        metaTitle\n        description {\n          json\n          links {\n            entries {\n              hyperlink {\n                ... on Page {\n                  __typename\n                  slug\n                }\n                ... on EditorialPage {\n                  __typename\n                  slug\n                }\n                ... on Campaign {\n                  __typename\n                  slug\n                }\n                ... on LandingPage {\n                  __typename\n                  slug\n                }\n              }\n            }\n          }\n        }\n        metaDescription\n        metaKeywords\n        alternativeTerms\n        componentsCollection(locale: $locale, limit: 8) {\n          items {\n            ...contentRow\n            ...productList\n            ...textBlock\n            ...brandBanner\n          }\n        }\n        footerBanner {\n          ...footerBanner\n        }\n      }\n    }\n  }\n": typeof types.LandingPageDocument,
};
const documents: Documents = {
    "\n  fragment asset on Asset {\n    __typename\n    url\n    size\n    title\n    width\n    height\n    contentType\n  }\n": types.AssetFragmentDoc,
    "\n  fragment brandBanner on BrandBanner {\n    __typename\n    bannerItemsCollection(limit: 20) {\n      items {\n        ... on ContentfulImage {\n          image {\n            ... on Asset {\n              __typename\n              url\n              size\n              title\n              width\n              height\n              contentType\n            }\n          }\n        }\n      }\n    }\n  }\n": types.BrandBannerFragmentDoc,
    "\n  fragment contentRow on ContentRow {\n    __typename\n    type\n    numberOfColumns\n    contentCollection(limit: 4) {\n      items {\n        ...splash\n      }\n    }\n  }\n": types.ContentRowFragmentDoc,
    "\n  fragment footerBanner on FooterBanner {\n    __typename\n    ... on FooterBanner {\n      title\n      linkText\n      desktopImage {\n        ...asset\n      }\n      mobileImage {\n        ...asset\n      }\n    }\n  }\n": types.FooterBannerFragmentDoc,
    "\n  fragment productList on ProductList {\n    __typename\n    linkText\n    heading\n    commerceData\n  }\n": types.ProductListFragmentDoc,
    "\n  fragment splash on Splash {\n    __typename\n    header\n    subheading\n    linkText\n    textColor\n    contentPosition\n    desktopVideo {\n      ...asset\n    }\n    desktopImage {\n      ...asset\n    }\n    mobileVideo {\n      ...asset\n    }\n    mobileImage {\n      ...asset\n    }\n    href {\n      ... on Page {\n        __typename\n        slug\n      }\n      ... on EditorialPage {\n        __typename\n        slug\n      }\n      ... on Campaign {\n        __typename\n        slug\n      }\n      ... on LandingPage {\n        __typename\n        slug\n      }\n      ... on NavigationLink {\n        title\n        internalLink {\n          ... on Page {\n            __typename\n            slug\n          }\n          ... on EditorialPage {\n            __typename\n            slug\n          }\n          ... on Campaign {\n            __typename\n            slug\n          }\n          ... on LandingPage {\n            __typename\n            slug\n          }\n        }\n      }\n    }\n  }\n": types.SplashFragmentDoc,
    "\n  fragment textBlock on TextBlock {\n    __typename\n    title\n    content {\n      json\n      links {\n        entries {\n          hyperlink {\n            ... on Page {\n              __typename\n              slug\n            }\n            ... on EditorialPage {\n              __typename\n              slug\n            }\n            ... on Campaign {\n              __typename\n              slug\n            }\n            ... on LandingPage {\n              __typename\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n": types.TextBlockFragmentDoc,
    "\n  query landingPage(\n    $order: LandingPageOrder = sys_publishedAt_DESC\n    $where: LandingPageFilter\n    $skip: Int = 0\n    $limit: Int = 1\n    $locale: String\n    $preview: Boolean = false\n  ) {\n    landingPageCollection(\n      order: [$order]\n      limit: $limit\n      where: $where\n      preview: $preview\n      locale: $locale\n      skip: $skip\n    ) {\n      items {\n        title\n        metaTitle\n        description {\n          json\n          links {\n            entries {\n              hyperlink {\n                ... on Page {\n                  __typename\n                  slug\n                }\n                ... on EditorialPage {\n                  __typename\n                  slug\n                }\n                ... on Campaign {\n                  __typename\n                  slug\n                }\n                ... on LandingPage {\n                  __typename\n                  slug\n                }\n              }\n            }\n          }\n        }\n        metaDescription\n        metaKeywords\n        alternativeTerms\n        componentsCollection(locale: $locale, limit: 8) {\n          items {\n            ...contentRow\n            ...productList\n            ...textBlock\n            ...brandBanner\n          }\n        }\n        footerBanner {\n          ...footerBanner\n        }\n      }\n    }\n  }\n": types.LandingPageDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment asset on Asset {\n    __typename\n    url\n    size\n    title\n    width\n    height\n    contentType\n  }\n"): (typeof documents)["\n  fragment asset on Asset {\n    __typename\n    url\n    size\n    title\n    width\n    height\n    contentType\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment brandBanner on BrandBanner {\n    __typename\n    bannerItemsCollection(limit: 20) {\n      items {\n        ... on ContentfulImage {\n          image {\n            ... on Asset {\n              __typename\n              url\n              size\n              title\n              width\n              height\n              contentType\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment brandBanner on BrandBanner {\n    __typename\n    bannerItemsCollection(limit: 20) {\n      items {\n        ... on ContentfulImage {\n          image {\n            ... on Asset {\n              __typename\n              url\n              size\n              title\n              width\n              height\n              contentType\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment contentRow on ContentRow {\n    __typename\n    type\n    numberOfColumns\n    contentCollection(limit: 4) {\n      items {\n        ...splash\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment contentRow on ContentRow {\n    __typename\n    type\n    numberOfColumns\n    contentCollection(limit: 4) {\n      items {\n        ...splash\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment footerBanner on FooterBanner {\n    __typename\n    ... on FooterBanner {\n      title\n      linkText\n      desktopImage {\n        ...asset\n      }\n      mobileImage {\n        ...asset\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment footerBanner on FooterBanner {\n    __typename\n    ... on FooterBanner {\n      title\n      linkText\n      desktopImage {\n        ...asset\n      }\n      mobileImage {\n        ...asset\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment productList on ProductList {\n    __typename\n    linkText\n    heading\n    commerceData\n  }\n"): (typeof documents)["\n  fragment productList on ProductList {\n    __typename\n    linkText\n    heading\n    commerceData\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment splash on Splash {\n    __typename\n    header\n    subheading\n    linkText\n    textColor\n    contentPosition\n    desktopVideo {\n      ...asset\n    }\n    desktopImage {\n      ...asset\n    }\n    mobileVideo {\n      ...asset\n    }\n    mobileImage {\n      ...asset\n    }\n    href {\n      ... on Page {\n        __typename\n        slug\n      }\n      ... on EditorialPage {\n        __typename\n        slug\n      }\n      ... on Campaign {\n        __typename\n        slug\n      }\n      ... on LandingPage {\n        __typename\n        slug\n      }\n      ... on NavigationLink {\n        title\n        internalLink {\n          ... on Page {\n            __typename\n            slug\n          }\n          ... on EditorialPage {\n            __typename\n            slug\n          }\n          ... on Campaign {\n            __typename\n            slug\n          }\n          ... on LandingPage {\n            __typename\n            slug\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment splash on Splash {\n    __typename\n    header\n    subheading\n    linkText\n    textColor\n    contentPosition\n    desktopVideo {\n      ...asset\n    }\n    desktopImage {\n      ...asset\n    }\n    mobileVideo {\n      ...asset\n    }\n    mobileImage {\n      ...asset\n    }\n    href {\n      ... on Page {\n        __typename\n        slug\n      }\n      ... on EditorialPage {\n        __typename\n        slug\n      }\n      ... on Campaign {\n        __typename\n        slug\n      }\n      ... on LandingPage {\n        __typename\n        slug\n      }\n      ... on NavigationLink {\n        title\n        internalLink {\n          ... on Page {\n            __typename\n            slug\n          }\n          ... on EditorialPage {\n            __typename\n            slug\n          }\n          ... on Campaign {\n            __typename\n            slug\n          }\n          ... on LandingPage {\n            __typename\n            slug\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment textBlock on TextBlock {\n    __typename\n    title\n    content {\n      json\n      links {\n        entries {\n          hyperlink {\n            ... on Page {\n              __typename\n              slug\n            }\n            ... on EditorialPage {\n              __typename\n              slug\n            }\n            ... on Campaign {\n              __typename\n              slug\n            }\n            ... on LandingPage {\n              __typename\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment textBlock on TextBlock {\n    __typename\n    title\n    content {\n      json\n      links {\n        entries {\n          hyperlink {\n            ... on Page {\n              __typename\n              slug\n            }\n            ... on EditorialPage {\n              __typename\n              slug\n            }\n            ... on Campaign {\n              __typename\n              slug\n            }\n            ... on LandingPage {\n              __typename\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query landingPage(\n    $order: LandingPageOrder = sys_publishedAt_DESC\n    $where: LandingPageFilter\n    $skip: Int = 0\n    $limit: Int = 1\n    $locale: String\n    $preview: Boolean = false\n  ) {\n    landingPageCollection(\n      order: [$order]\n      limit: $limit\n      where: $where\n      preview: $preview\n      locale: $locale\n      skip: $skip\n    ) {\n      items {\n        title\n        metaTitle\n        description {\n          json\n          links {\n            entries {\n              hyperlink {\n                ... on Page {\n                  __typename\n                  slug\n                }\n                ... on EditorialPage {\n                  __typename\n                  slug\n                }\n                ... on Campaign {\n                  __typename\n                  slug\n                }\n                ... on LandingPage {\n                  __typename\n                  slug\n                }\n              }\n            }\n          }\n        }\n        metaDescription\n        metaKeywords\n        alternativeTerms\n        componentsCollection(locale: $locale, limit: 8) {\n          items {\n            ...contentRow\n            ...productList\n            ...textBlock\n            ...brandBanner\n          }\n        }\n        footerBanner {\n          ...footerBanner\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query landingPage(\n    $order: LandingPageOrder = sys_publishedAt_DESC\n    $where: LandingPageFilter\n    $skip: Int = 0\n    $limit: Int = 1\n    $locale: String\n    $preview: Boolean = false\n  ) {\n    landingPageCollection(\n      order: [$order]\n      limit: $limit\n      where: $where\n      preview: $preview\n      locale: $locale\n      skip: $skip\n    ) {\n      items {\n        title\n        metaTitle\n        description {\n          json\n          links {\n            entries {\n              hyperlink {\n                ... on Page {\n                  __typename\n                  slug\n                }\n                ... on EditorialPage {\n                  __typename\n                  slug\n                }\n                ... on Campaign {\n                  __typename\n                  slug\n                }\n                ... on LandingPage {\n                  __typename\n                  slug\n                }\n              }\n            }\n          }\n        }\n        metaDescription\n        metaKeywords\n        alternativeTerms\n        componentsCollection(locale: $locale, limit: 8) {\n          items {\n            ...contentRow\n            ...productList\n            ...textBlock\n            ...brandBanner\n          }\n        }\n        footerBanner {\n          ...footerBanner\n        }\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;